version: '3.9'

services:
  go-app:
    build:
      context: ..  # Корень проекта (VK_Test_Task)
      dockerfile: Dockerfile
    container_name: poll-bot
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ../poll_bot/config:/app/config  # Монтируем конфиги
      - ../deploy:/app/deploy
    networks:
      - mattermost_network

  tarantool:
    image: tarantool/tarantool:latest
    container_name: tarantool
    restart: always
    ports:
      - "3301:3301"
    volumes:
      - ../deploy/migrations/init.lua:/opt/tarantool/init.lua:ro
    command: tarantool /opt/tarantool/init.lua
    networks:
      - mattermost_network
    env_file:
      - ../deploy/.env

networks:
  mattermost_network:
    external: true